### PR TITLE
Updating samples

### PR DESCRIPTION
**Pull request by jansabbe**
AWS did some updates so I
* Added a Go example
* Updated C# example to .net core 2.0
* Used latest version for python

### CODE REVIEW

**Comment by theburningmonk** [comment]
Thank you so much for doing this!

**Comment by jansabbe** [comment]
No problem, I really enjoyed your blog article and was interested in the current state. I'm running some tests now.

I did notice that there might be an issue with `sls deploy`. For both Nodejs and Python it is able to detect that the source files didn't change, so it doesn't upload a new version. They don't get cold starts, unlike java and c#. Using `sls deploy --force` should force uploading a new version. I ran some initial tests with `---force`, your conclusions are still valid. Python and Node are way faster at cold starts. Go is in the same league as Python and Node.

**Comment by theburningmonk** [comment]
Yes, that change came in a recent update to serverless framework, so in the build.sh we'll need to add `--force` flag.

Now that you've done all the hard work, I'll run the experiment again myself this weekend and update the post. Are you seeing Go being slightly ahead of Python and Node by any chance?

**Comment by jansabbe** [comment]
From fast to slow, I'm seeing: Python, Go, NodeJs, C# and last Java. So Python is still ahead of Go, but Go does beat NodeJS. C# and Java switched places with the last .Net Core update, but both are still way slower than the others.

Go has the largest binary size at 2.9MB (compiled binaries include the Go runtime), while java has 2MB and C# has 207KB. So what you observed in your article holds up. Bigger deployment package size does not increase coldstart time. That is just plain weird :-)

My plot.ly is here https://plot.ly/~jansabbe/6/csharp-java-python-nodejs6-golang/ (partial run)

**Pull request merged**
